[build]
  command = "npm run build"
  publish = "dist/numeros-da-sorte/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.9.0"
  NPM_VERSION = "10.2.3" 